ALTER TABLE vehicle_telemetry
    ADD COLUMN IF NOT EXISTS autonomy_mode  VARCHAR(20) DEFAULT 'AUTONOMOUS',
    ADD COLUMN IF NOT EXISTS lidar_ok       BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS camera_ok      BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS camera_blinded BOOLEAN DEFAULT FALSE;
